//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM İlişkisi Meta Verileri

[assembly: EdmRelationshipAttribute("Model", "FK_Borrowed_Book", "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication15.Book), "Borrowed", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication15.Borrowed), true)]

#endregion

namespace WebApplication15
{
    #region Bağlamlar
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    public partial class Library_DatabaseEntities : ObjectContext
    {
        #region Oluşturucular
    
        /// <summary>
        /// Yeni Library_DatabaseEntities nesnesini, uygulama yapılandırma dosyasının 'Library_DatabaseEntities' bölümünde bulunan bağlantı dizesini kullanarak başlatır.
        /// </summary>
        public Library_DatabaseEntities() : base("name=Library_DatabaseEntities", "Library_DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Yeni bir Library_DatabaseEntities nesnesi başlatın.
        /// </summary>
        public Library_DatabaseEntities(string connectionString) : base(connectionString, "Library_DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Yeni bir Library_DatabaseEntities nesnesi başlatın.
        /// </summary>
        public Library_DatabaseEntities(EntityConnection connection) : base(connection, "Library_DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Kısmi Yöntemler
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Özellikleri
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        public ObjectSet<Book> Book
        {
            get
            {
                if ((_Book == null))
                {
                    _Book = base.CreateObjectSet<Book>("Book");
                }
                return _Book;
            }
        }
        private ObjectSet<Book> _Book;
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        public ObjectSet<Borrowed> Borrowed
        {
            get
            {
                if ((_Borrowed == null))
                {
                    _Borrowed = base.CreateObjectSet<Borrowed>("Borrowed");
                }
                return _Borrowed;
            }
        }
        private ObjectSet<Borrowed> _Borrowed;

        #endregion

        #region AddTo Yöntemleri
    
        /// <summary>
        /// Book EntitySet'e yeni nesne ekleme için Deprecated Yöntemi. Bunun yerine, ilişkili ObjectSet&lt;T&gt; özelliğinin .Add yöntemini kullanmayı deneyin.
        /// </summary>
        public void AddToBook(Book book)
        {
            base.AddObject("Book", book);
        }
    
        /// <summary>
        /// Borrowed EntitySet'e yeni nesne ekleme için Deprecated Yöntemi. Bunun yerine, ilişkili ObjectSet&lt;T&gt; özelliğinin .Add yöntemini kullanmayı deneyin.
        /// </summary>
        public void AddToBorrowed(Borrowed borrowed)
        {
            base.AddObject("Borrowed", borrowed);
        }

        #endregion

    }

    #endregion

    #region Varlıklar
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Book")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Book : EntityObject
    {
        #region Factory Yöntemi
    
        /// <summary>
        /// Yeni bir Book nesnesi oluşturun.
        /// </summary>
        /// <param name="id">ID özelliğinin ilk değeri.</param>
        /// <param name="name">Name özelliğinin ilk değeri.</param>
        /// <param name="writer">Writer özelliğinin ilk değeri.</param>
        /// <param name="imgUrl">ImgUrl özelliğinin ilk değeri.</param>
        /// <param name="status">Status özelliğinin ilk değeri.</param>
        public static Book CreateBook(global::System.Int32 id, global::System.String name, global::System.String writer, global::System.String imgUrl, global::System.Boolean status)
        {
            Book book = new Book();
            book.ID = id;
            book.Name = name;
            book.Writer = writer;
            book.ImgUrl = imgUrl;
            book.Status = status;
            return book;
        }

        #endregion

        #region Basit Özellikler
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Writer
        {
            get
            {
                return _Writer;
            }
            set
            {
                OnWriterChanging(value);
                ReportPropertyChanging("Writer");
                _Writer = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Writer");
                OnWriterChanged();
            }
        }
        private global::System.String _Writer;
        partial void OnWriterChanging(global::System.String value);
        partial void OnWriterChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ImgUrl
        {
            get
            {
                return _ImgUrl;
            }
            set
            {
                OnImgUrlChanging(value);
                ReportPropertyChanging("ImgUrl");
                _ImgUrl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ImgUrl");
                OnImgUrlChanged();
            }
        }
        private global::System.String _ImgUrl;
        partial void OnImgUrlChanging(global::System.String value);
        partial void OnImgUrlChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Boolean _Status;
        partial void OnStatusChanging(global::System.Boolean value);
        partial void OnStatusChanged();

        #endregion

    
        #region Gezinme Özellikleri
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Borrowed_Book", "Borrowed")]
        public EntityCollection<Borrowed> Borrowed
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Borrowed>("Model.FK_Borrowed_Book", "Borrowed");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Borrowed>("Model.FK_Borrowed_Book", "Borrowed", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Borrowed")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Borrowed : EntityObject
    {
        #region Factory Yöntemi
    
        /// <summary>
        /// Yeni bir Borrowed nesnesi oluşturun.
        /// </summary>
        /// <param name="id">ID özelliğinin ilk değeri.</param>
        /// <param name="bookID">BookID özelliğinin ilk değeri.</param>
        /// <param name="date">Date özelliğinin ilk değeri.</param>
        /// <param name="person">Person özelliğinin ilk değeri.</param>
        public static Borrowed CreateBorrowed(global::System.Int32 id, global::System.Int32 bookID, global::System.DateTime date, global::System.String person)
        {
            Borrowed borrowed = new Borrowed();
            borrowed.ID = id;
            borrowed.BookID = bookID;
            borrowed.Date = date;
            borrowed.Person = person;
            return borrowed;
        }

        #endregion

        #region Basit Özellikler
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BookID
        {
            get
            {
                return _BookID;
            }
            set
            {
                OnBookIDChanging(value);
                ReportPropertyChanging("BookID");
                _BookID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BookID");
                OnBookIDChanged();
            }
        }
        private global::System.Int32 _BookID;
        partial void OnBookIDChanging(global::System.Int32 value);
        partial void OnBookIDChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Person
        {
            get
            {
                return _Person;
            }
            set
            {
                OnPersonChanging(value);
                ReportPropertyChanging("Person");
                _Person = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Person");
                OnPersonChanged();
            }
        }
        private global::System.String _Person;
        partial void OnPersonChanging(global::System.String value);
        partial void OnPersonChanged();

        #endregion

    
        #region Gezinme Özellikleri
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Borrowed_Book", "Book")]
        public Book Book
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Book>("Model.FK_Borrowed_Book", "Book").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Book>("Model.FK_Borrowed_Book", "Book").Value = value;
            }
        }
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Book> BookReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Book>("Model.FK_Borrowed_Book", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Book>("Model.FK_Borrowed_Book", "Book", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
